services:
  - type: worker               # ❗️ نوع سرویس باید Worker باشه، نه Web
    name: NeuraForgeBot
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true

    envVars:
      - key: BOT_TOKEN
        fromEnvVar: BOT_TOKEN
      - key: ADMIN_ID
        fromEnvVar: ADMIN_ID
      - key: DB_URL
        fromEnvVar: DB_URL
      - key: CRYPTO_API_KEY
        fromEnvVar: CRYPTO_API_KEY
      - key: USDT_WALLET
        fromEnvVar: USDT_WALLET
      - key: BNB_WALLET
        fromEnvVar: BNB_WALLET
      - key: TRX_WALLET
        fromEnvVar: TRX_WALLET
      - key: AI_CHAT_ENABLED
        fromEnvVar: AI_CHAT_ENABLED
      - key: GPT_API_KEY
        fromEnvVar: GPT_API_KEY
